version: '3'

services:
  custom-grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgdev
    container_name: queryiq-pg
volumes:
  grafana-storage:
