// import { type NextPage } from "next";
import Header from "../components/Header";
import MainContainer from "../containers/MainContainer";
// import { useSession } from "next-auth/react";
import Head from "next/head";
// import Link from "next/link";
// import { api } from "~/utils/api";

const Homepage: React.FC = () => {
  return (
    <>
      <Head>
        <title>Query IQ Homepage</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-h-full w-screen min-w-full max-w-full bg-black">
        <Header />
        <MainContainer />
      </main>
    </>
  );
};

export default Homepage;
